name: Release Creation

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            #Substitute the Manifest and Download URLs in the module.json
            - name: Substitute Manifest and Download Links For Versioned Ones
              id: sub_manifest_link_version
              uses: microsoft/variable-substitution@v1
              with:
                  files: "module.json"
              env:
                  version: ${{github.event.release.tag_name}}
                  manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
                  download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/azgaar-foundry.zip

            # create a zip file with all files required by the module to add to the release
            - run: zip -r ./azgaar-foundry.zip module.json css/ templates/ images/ main.js README.md LICENSE

            # Create a release for this specific version
            - name: Update Release with Files
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true # set this to false if you want to prevent updating existing releases
                  name: ${{ github.event.release.name }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./module.json, ./azgaar-foundry.zip"
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}

            # Update the 'latest' release
            - name: Create Release
              id: create_latest_release
              uses: ncipollo/release-action@v1
              if: endsWith(github.ref, 'master')
              with:
                  allowUpdates: true
                  name: Latest
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./module.json,./azgaar-foundry.zip"
                  tag: latest
                  body: ${{ github.event.release.body }}

            # Publish this new version to the Foundry VTT Module Listing
            - name: FoundryVTT AutoPublish
              uses: Varriount/fvtt-autopublish@v1.0.9
              with:
                  username: ${{ secrets.FOUNDRY_ADMIN_USER }}
                  password: ${{ secrets.FOUNDRY_ADMIN_PW }}
                  module-id: 1314
                  manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
                  manifest-file: module.json
